# Generated by Django 5.1.5 on 2025-01-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
